In [7]:
import torch


In [22]:
a = torch.randn(4, 4)
print(a)
print(torch.max(a, 1))#返回两个东西，一个是每一行的最大值，一个是在行中的位置

tensor([[ 1.2020,  0.4292,  0.2641, -0.7286],
        [-0.0967,  0.0076,  1.3150, -1.0966],
        [-0.4860, -1.2695,  1.1603, -0.6663],
        [-0.1685, -1.1590,  1.6563,  0.6749]])
torch.return_types.max(
values=tensor([1.2020, 1.3150, 1.1603, 1.6563]),
indices=tensor([0, 2, 2, 2]))
tensor([[ 1.2020,  0.4292,  0.2641, -0.7286],
        [-0.0967,  0.0076,  1.3150, -1.0966],
        [-0.4860, -1.2695,  1.1603, -0.6663],
        [-0.1685, -1.1590,  1.6563,  0.6749]])


In [13]:
x = torch.randn((3,4))
x.size(0)

3

In [16]:
a = torch.tensor([[1,2,3],[2,3,4],[1,2,3],[6,3,2]],[2,1,3],[2,4,1])
b = torch.tensor([1,2,3,1,2,4])
train_set = torch.utils.data.TensorDataset(a,b)

In [20]:
trainloader = torch.utils.data.DataLoader(train_set,batch_size=2,shuffle=True)
for i,data in enumerate(trainloader):
    print(f'第{i}比数据为{data}')
print(len(trainloader))

第0比数据为[tensor([[6, 3, 2],
        [1, 2, 3]]), tensor([1, 1])]
第1比数据为[tensor([[2, 3, 4],
        [1, 2, 3]]), tensor([2, 3])]
2


In [24]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,3,2])
a==b

tensor([ True, False, False])

In [26]:
(a==b).sum().item()

1